Convert to tudscr-based document class
TUD-OS/latex-template pull request #23
Opened 2024-11-07 14:11 UTC by l3nkz

@schirmeier Do you like this title page and general style more?

2024-11-07 20:38 UTC, schirmeier requested changes
Nice! Thanks!
(Just some details to be fixed)

2024-11-07 20:38 UTC, schirmeier commented on content/00_title.tex
> +    %\chair{Lehrstuhl für Betriebssysteme}
Professur für ...

2024-11-07 20:38 UTC, schirmeier commented on content/00_title.tex
> +    \professor{Porf.\ Dr.-Ing.\ Horst Schirmeier}
what's a "Porf"? :-)

2024-11-07 20:38 UTC, schirmeier commented on content/00_title.tex
> +    \graduation[Dipl-Inf]{Diplom Informatiker*in}
\graduation[Dipl.-Inf.]{Diplom-Informatiker*in}

2024-11-13 17:10 UTC, schirmeier commented
Please make the third suggested change to 00_title.tex, too.

(Why does CI fail?)

2024-11-14 22:08 UTC, l3nkz commented
Should all be included now. I also rebased on top of the CI fix from @phip1611. Maybe this fixes the CI problem

2024-11-15 10:15 UTC, phip1611 commented
Should be fixed with #24. Merge it and rebase this onto it :)

2025-01-12 15:16 UTC, Wer-Wolf commented
What is the current status of this PR?

2025-09-30 08:49 UTC, merged