make headings look more professional
TUD-OS/latex-template pull request #6
Opened 2022-02-11 17:31 UTC by phip1611

Style is of course an opinion. However, I think these small changes make the thesis look much more professional. Furthermore,
if someone doesn't want it, it can be easily removed.

What do you think?

2022-02-14 09:41 UTC, blitz commented on preamble/style.tex
> +%   Default is sans-serif which looks kind of unprofessionel with the default font family.
nit: "unprofessional"

2022-02-14 09:42 UTC, blitz commented on preamble/style.tex
> +%   siehe: https://mirror.physik.tu-berlin.de/pub/CTAN/macros/latex/contrib/koma-script/doc/scrguide.pdf
nit: "see"

2022-02-14 09:42 UTC, blitz commented on preamble/style.tex
> +% With the fancyhdr package we can let all pages look more professionel.
nit: same type as above

2022-02-14 09:44 UTC, blitz requested changes
I'm pretty neutral about the font changes, but the headers do look more professional.

Will merge when typos are squashed.

2022-02-14 10:09 UTC, phip1611 commented
fixed @blitz

2022-03-24 10:20 UTC, l3nkz commented
I don't have any hard feelings regarding the font change. I am going to merge it like this. The comment in the code is already explaining everything. So I think this is fine. If any student that uses the template wants to change it, he/she can do as stated in the comment. Thank you very much for your work.

2022-03-24 10:20 UTC, merged