comment/hint for bibliography
TUD-OS/latex-template pull request #9
Opened 2022-02-12 08:40 UTC by phip1611

Small hint. This is something everyone has to decide by themselves. Therefore, I've only given the pointer to this option in the comment.

2022-02-12 08:55 UTC, Nils-TUD commented
Good hint! I think we should go one step further for the author list, though. It can be acceptable to not list all authors if there is a page limit for references. However, such limit does not exist for a student thesis. Therefore, listing all authors should be the default to give credit to all authors (I am actually wondering why it is not already the default).

2022-02-12 09:10 UTC, phip1611 commented
I've updated the PR @Nils-TUD

2022-02-14 09:57 UTC, blitz commented on preamble/packages.tex
> +% You can chose style "numeric" instead which is common in many papers.
nit: "choose"

2022-02-14 09:58 UTC, blitz commented on preamble/packages.tex
> +% Without "maxbibnames=99" the biblopgraphy entries only contain "First Name et al."
nit: bibliography?

2022-02-14 09:58 UTC, blitz requested changes
Looks good when the typos are fixed.

2022-02-14 10:06 UTC, phip1611 commented
Fixed @blitz

2022-03-21 10:51 UTC, merged